spring:
  application:
    name: ticketing

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:8001/${POSTGRES_DB:ticketing}
    username: ${POSTGRES_USER:titanfall}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
server:
  port: 8080
